comment:
  behavior: default
  layout: header, diff
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
ignore:
- ^tests.*
