#
# This codecov.yml is the default configuration for
# all repositories on Codecov. You may adjust the settings
# below in your own codecov.yml in your repository.
#
coverage:
  status:
    project: # see https://docs.codecov.com/docs/commit-status
      default:
        target: auto #default
        threshold: 0%
        # TODO make PR block on coverage drop?
        informational: true
comment:                  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: false #
