[build-system]
requires = ["hatchling>=1.8.0", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["era5cli"]

[tool.hatch.version]
path = "era5cli/__version__.py"

[project]
name = "era5cli"
description = "A command line interface to download ERA5 data from the Copernicus Climate Data Store. https://climate.copernicus.eu/.."
readme = "README.md"
license = { text = "Apache Software License" }
requires-python = ">=3.10"
authors = [
    {name = "Ronald van Haren"},
    {name = "Jaro Camphuijsen"},
    {name = "Yifat Dzigan"},
    {name = "Niels Drost"},
    {name = "Fakhereh Alidoost"},
    {name = "Bouwe Andela"},
    {name = "Jerom Aerts"},
    {name = "Berend Weel"},
    {name = "Rolf Hut"},
    {name = "Klaus Zimmermann"},
    {name = "Peter Kalverla"},
    {name = "Barbara Vreede", email="b.vreede@esciencecenter.nl"},
    {name = "Aytaç Paçal"},
    {name = "Stef Smeets"},
    {name = "Stefan Verhoeven"},
    {name = "Elizaveta Malinina"},
    {name = "Bart Schilperoort", email = "b.schilperoort@esciencecenter.nl" },
    {name = "Mark Melotto"}
]
keywords = [
  "ERA-5",
  "climate data",
  "cds api",
  "cds download",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "License :: OSI Approved :: Apache Software License",
  "Natural Language :: English",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "cdsapi>=0.7.4",
  "pathos",
  "PTable",
  "netCDF4"
]
dynamic = ["version"]

[project.scripts]
era5cli="era5cli.cli:main"

[project.optional-dependencies]
dev = [
  "hatch",
  "bump-my-version",
  "ruff",
  "pytest",
  "pytest-cov",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-gen-files",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.envs.default]
features = ["dev",]

[tool.hatch.envs.default.scripts]
lint = [
    "ruff check .",
    "ruff format --check --diff .",
]
format = [
    "ruff check --fix .",
    "ruff format .",
]
test = ["pytest",]
coverage = ["pytest --cov=era5cli --cov-report term --cov-report xml:cov.xml tests/"]

[tool.hatch.envs.docs]
features = ["docs",]

[tool.hatch.envs.docs.scripts]
build = ["mkdocs build",]
serve = ["mkdocs serve",]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "@overload",
  "if TYPE_CHECKING:",
  "if typing.TYPE_CHECKING:"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["era5cli"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]
ignore = [
    "E501"
]